SET mapred.job.name='day-changed-trade-analyze 每天变化订单数据分析';
set hive.tez.container.size=6144;
set hive.cbo.enable=true;
SET hive.exec.compress.output=true;
SET mapred.max.split.size=512000000;
set mapred.min.split.size.per.node=100000000;
set mapred.min.split.size.per.rack=100000000;
set hive.input.format=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat;
SET mapred.output.compression.type=BLOCK;
SET mapreduce.map.output.compress=true;
SET mapred.output.compression.codec=org.apache.hadoop.io.compress.SnappyCodec;
SET hive.exec.dynamic.partition.mode=nonstrict;
SET hive.exec.dynamic.partition=true;
SET mapreduce.reduce.shuffle.input.buffer.percent =0.6;
SET hive.exec.max.created.files=655350;
SET hive.exec.max.dynamic.partitions=10000000;
SET hive.exec.max.dynamic.partitions.pernode=10000000;
set hive.stats.autogather=false;
set hive.merge.mapfiles = true;
set hive.merge.mapredfiles=true;
set hive.merge.size.per.task = 512000000;
set hive.support.concurrency=false;

-- 删除所有中间临时结果集
drop table if exists dw_rfm.b_first_buy_history_base;
drop table if exists dw_rfm.b_last_year_history_base;
drop table if exists dw_rfm.b_last_tyear_history_base;
drop table if exists dw_rfm.b_before_tyear_history_base;
drop table if exists dw_rfm.plat_first_buy_history_all_temp;
drop table if exists dw_rfm.plat_first_buy_history_all_temp;
drop table if exists dw_rfm.tenant_first_buy_history_all_temp;